### ISSUE TITLE
enhancement: create a header for the ethernet port

### ISSUE THREAD

**Issue by stapelberg** [freetserv/freetserv#26]
We can just not populate it on 3 of the 4 boards.

**Comment by jaredmauch** [comment]
I can tackle this one.  It's super simple.

**Comment by stapelberg** [comment]
Great, looking forward to your pull request (please keep the changes as small as possible). Let me know if you need anything.

**Comment by jaredmauch** [comment]
Well, I haven't completed it, but thought I'd ask your feelings on this placement first before I fix all the impacted traces, length matching, etc.

![screenshot 2016-01-04 10 49 30](https://cloud.githubusercontent.com/assets/8975853/12093445/f3ebbb5e-b2d0-11e5-89d3-949ba922ab1e.png)

**Comment by stapelberg** [comment]
Thanks for the preview. I think the general position is fine, especially since the daisy-chain connector on the right hand side does not need to be populated for the right-most board.

Here are a couple of thoughts:
- Is the part that you’re adding available on Digi-Key?
- Can you come up with a way to route it without touching any other traces to make this change as non-invasive as possible? It looks to me like it might be possible to use traces on the top layer that go from top to bottom on the right hand side of the PCB, all the way to P12.

**Comment by jaredmauch** [comment]
Yes, it's available on Digikey (WM5467-ND) and there are other variants which are more expensive or cheaper, eg: WM5468-ND which are pin compatible.  It's not really possible without moving part D2, which I assume is ok.  The traces related to D2 have to be re-routed.  This would obviously impact anyone using a PnP machine to place parts.

Is there a common .lbr file for freetserv I should put these parts in, or should that go in the pull?  I could also just email you the files offline.

**Comment by stapelberg** [comment]
Moving D2 is okay. We don’t have a common .lbr file yet, but you’re welcome to start one, or just let Eagle embed the lbr file into the brd/sch files as appropriate (which is what we currently do).

**Comment by jaredmauch** [comment]
taking a fresh look at this, i'm concerned that having the ethernet pin 5 shared with the RS232 ground may cause signal issues, have you had issues with the soldered cable connection being shared with the uart12 level shifter?

**Comment by jaredmauch** [comment]
since this was merged, should this be closed?

**Comment by stapelberg** [comment]
Yep, thanks

**Comment by paravoid** [comment]
I've noticed that the documentation (assembly.html) still documents a manual way, and references this issue as a work-in-progress. Not sure how this should be updated though.

**Comment by stapelberg** [comment]
@jaredmauch Any thoughts on this? Personally, I don’t have a build with the new ethernet port solution, and don’t plan on building one right now.
