### ISSUE TITLE
Wrong Digikey Part for QG1 

### ISSUE THREAD

**Issue by jhorisberger** [freetserv/freetserv#41]
The 12MHz Oscilator in the BOM from eagle and on the Homepage dos not fit the footprint on the PCB. From the Silkscreen on the PCB i gather that it should be form the ASFL1 series (instead of ASV). I found this part:  Abracon LLC ASFL1-12.000MHZ-EK-T (535-9253-1-ND ) which I think should be ok? (almost identical specs and right footprint)

**Comment by stapelberg** [comment]
Thanks for reporting this. I just had a chance to check my inbox for orders, and indeed I did order the 535-9253-1-ND after I must have realized that the other oscillator has the wrong form factor :).

I’ll fix this in a second.
