### ISSUE TITLE
BOM DAISY_IN Digi-Key Part 732-2863-ND is a 10 pin Header

### ISSUE THREAD

**Issue by lairsdragon** [freetserv/freetserv#42]
Hi

The Digi-Key Part Number 732-2863-ND is a 10 pin Header. The Wurth Elektronik part number in the BOM.txt is correct but I was not able to find that part at Digi-Key.

The Wurth Elektronik part number on the  website (in fts-bom-pcbparts.html) is wrong.

cheerio
    Steve

**Comment by stapelberg** [comment]
Thanks! This is now fixed.

**Comment by lairsdragon** [comment]
Hi Michael

The Digi-Key Part Number points still to a 10 pin Header;

cheerio
    Steve

**Comment by stapelberg** [comment]
I can’t find a more suitable part number on Digi-Key. You can easily cut the 10-pin connector to be a 4-pin connector, so it’s no big deal. If you have a better part number, let me know.
